### ISSUE TITLE
an interseting problem about baselines

### ISSUE THREAD

**Issue by onefanwu** [uwdb/MaskSearch#1]
Hi @dongheuw
The community version of SciDB has always been available for download. Many papers have used it as a baseline. However, the MaskSearch paper says it is no longer available. I happened to read this paper and wanted to correct it.

SciDB Community Version: https://downloads.paradigm4.com/community/
Document: https://paradigm4.atlassian.net/wiki/spaces/scidb/overview

**Comment by dongheuw** [comment]
Does it support Ubuntu 18.04?

The reason why the paper says that was that we posted an issue under SciDB-py (https://github.com/Paradigm4/SciDB-Py/issues/161), and that we heard from Paradigm4 that they "have moved away from the community edition, just like tileDB has".

**Comment by onefanwu** [comment]
Okay. The latest community release of SciDB is only supported up to Ubuntu 16.04. TileDB is supported in Ubuntu 18.04, and I've been using it.

https://github.com/rvernica/docker-library/tree/master/scidb
https://docs.tiledb.com/main/how-to/installation/building-from-source
https://github.com/TileDB-Inc/TileDB

**Comment by dongheuw** [comment]
> Okay. The latest community release of SciDB is only supported up to Ubuntu 16.04. TileDB is supported in Ubuntu 18.04, and I've been using it.
> 
> https://github.com/rvernica/docker-library/tree/master/scidb https://docs.tiledb.com/main/how-to/installation/building-from-source https://github.com/TileDB-Inc/TileDB

I'm aware that TileDB supports Ubuntu 18.04 :)

**Comment by onefanwu** [comment]
> > Okay. The latest community release of SciDB is only supported up to Ubuntu 16.04. TileDB is supported in Ubuntu 18.04, and I've been using it.
> > https://github.com/rvernica/docker-library/tree/master/scidb https://docs.tiledb.com/main/how-to/installation/building-from-source https://github.com/TileDB-Inc/TileDB
> 
> I'm aware that TileDB supports Ubuntu 18.04 :)

Thank you so much for your clarification, MaskSearch is an excellent work. In reality, I just wanted to mention that the TileDB Community Edition does support Ubuntu 18.04 and should still be available on GitHub. Of course, this is all just casual conversation  :D.
